### ISSUE TITLE
Facility Endpoints

### ISSUE THREAD

**Issue by ish2028** [KeiserCorp/Keiser.Metrics.SDK#11]
Here is to get started.  
- [x] facilitySession:list (used to display members that are checked in)
- [x] facilityRelationship:facilityList (used to display employees for an active facility)
- [x] facilityRelationship:facilityUpdate (removed employee/member for an active facility, update employee role)
- [x] facilityRelationship:facilityCreate (create a member/employee account)
- [x] facilityRelationshipRequest:facilityCreate (used to request access to an existing Keiser Account)
- [x] userInBodyIntegration:show (Member Inbody data)
- [x] userInBodyIntegration:delete (Remove Members Inbody data)
- [x] facilityKioskToken:userLogin (Logs in member from Kiosk)
- [x] auth:facilityWelcomeFulfillment 
- [x] facilityAccessControlIPRange:list (Facility Settings)
- [x] facilityAccessControlIPRange:create
- [x] facilityAccessControlIPRange:update
- [x] facilityAccessControlIPRange:delete
- [x] facilityStrengthMachine:list 
- [x] facilityStrengthMachine:update (Updates the machine location)
- [x] facilityStrengthMachine:delete
- [x] facilityStrengthMachine:createEchip
- [x] facilitySession:status (Display members session plans)
- [x] facilitySession:start
- [x] facilityKiosk:sessionStart
- [x] facilityKioskToken:create
- [x] facilityKioskToken:delete
- [x] facilityAccessControlKiosk:show
- [x] facilityAccessControlKiosk:update
- [x] facilitySession:end
- [x] facilitySession:endEchip
- [x] facilityKiosk:sessionEndEchip
- [x] facilitySession:updateEchip
- [x] facilityToken:sessionUpdateEchip (Kiosk side)
- [x] facilityConfiguration:show
- [x] facilityConfiguration:update
- [x] weightMeasurement:importInBodyCSV
- [x] weightMeasurement:importInBody
 
Just want to make sure that the SDK is also going to be compatible with Kiosk Mode when the token is for a Kiosk.

**Comment by ish2028** [comment]
I assume other endpoints like `session:list` will work on the model for the user once I have the users object so that I can get the data relating to that user.

**Comment by bayssmekanique** [comment]
Requires full scope models:
- [ ] `userInBodyIntegration` (Need InBody integration endpoints for `weightMeasurement` too)
- [ ] `facilitySession`
- [ ] `facilityRelationship`
- [ ] `facilityRelationshipRequest`
- [ ] `facilityStrengthMachine`
- [ ] `facilitySession`
- [ ] `facilityKiosk`
- [ ] `facilityKioskToken`
- [ ] `facilityConfiguration`
- [ ] `facilityAccessControlKiosk`
- [ ] `facilityAccessControlIPRange`
