### ISSUE TITLE
Add SSO url generator

### ISSUE THREAD

**Issue by bayssmekanique** [KeiserCorp/Keiser.Metrics.SDK#128]

**Comment by Mravuri96** [comment]
| Endpoint| Required | Optional |
| :---        |    :----:   |          ---: |
| sso | - |  returnUrl , email |
| signup |  -  | returnUrl , email |

**Comment by bayssmekanique** [comment]
@Mravuri96, why would I ever hit `sso/signup` or `sso/account-recovery` directly from an app?

**Comment by Mravuri96** [comment]
Bryces' login page had a dedicated  login and sign buttons so 🤷🏼

**Comment by ish2028** [comment]
I don't think we need `sso/signup` and `sso/account-recovery`.  Bryce's login page was designed and thought about before SSO so that will most likely change.

**Comment by bayssmekanique** [comment]
We'll keep the pages (for now), but I won't put the endpoints into the SDK until we know how/why we would use them.

**Comment by ish2028** [comment]
Correct, we need the pages.  But the SDK doesn't need to know about them.
