### ISSUE TITLE
Add user machine adjustments

### ISSUE THREAD

**Issue by JohnathanHill** [KeiserCorp/Keiser.Metrics.SDK#175]
## User Machine Adjustments

See https://github.com/KeiserCorp/Keiser.Metrics.API/issues/679

**Comment by ish2028** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Machine Adjustments for SDK](https://trello.com/c/GkVHl3GM/6-machine-adjustments-for-sdk)
